http.host: "0.0.0.0"
xpack.monitoring.enabled: false

path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
path.data: /usr/share/logstash/data

pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

queue.type: memory
queue.max_bytes: 1gb

dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb

log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# Allow config reload
config.reload.automatic: true
config.reload.interval: 3s
