apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: microservices-logs-*
    timeField: "@timestamp"
    editable: true
    jsonData:
      interval: Daily
      timeInterval: "10s"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
