global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-service:8002']
  - job_name: 'todo-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-service:8001']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
