api.enabled: true
api.environment: production
api.http.host: 0.0.0.0
api.http.port: 9600
cluster.name: microservices-cluster
config.reload.automatic: true
config.reload.interval: 3s
config.support_escapes: true
config.test_and_exit: false
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb
dead_letter_queue.retain.age: 7d
http.host: 0.0.0.0
http.port: 9600
log.format: plain
log.level: ${LOG_LEVEL}
node.name: logstash-node
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /var/log/logstash
path.settings: /usr/share/logstash/config
pipeline.batch.delay: 50
pipeline.batch.size: 250
pipeline.unsafe_shutdown: false
pipeline.workers: 4
queue.max_bytes: 2gb
queue.page_capacity: 64mb
queue.type: memory
slowlog.threshold.debug: 500ms
slowlog.threshold.info: 1s
slowlog.threshold.trace: 100ms
slowlog.threshold.warn: 2s
xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED}
