allow_superuser: true
api.enabled: true
api.environment: production
api.http.host: 0.0.0.0
api.http.port: 9600
config.reload.automatic: true
config.reload.interval: 3s
config.support_escapes: true
config.test_and_exit: false
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb
dead_letter_queue.retain.age: 7d
log.format: plain
log.level: ${LOG_LEVEL}
node.name: logstash-node
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
path.settings: /usr/share/logstash/config
pipeline.batch.delay: 50
pipeline.batch.size: 250
pipeline.buffer.type: heap
pipeline.unsafe_shutdown: false
pipeline.workers: 4
queue.max_bytes: 2gb
queue.page_capacity: 64mb
queue.type: memory
xpack.monitoring.enabled: ${XPACK_MONITORING_ENABLED}
