# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"\x07\n\x05\x45mpty\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"%\n\x08TodoList\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\"\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\"A\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdd\x01\n\x0bTodoService\x12\'\n\x08GetTodos\x12\x0b.todo.Empty\x1a\x0e.todo.TodoList\x12\x31\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\n.todo.Todo\x12\x31\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\n.todo.Todo\x12?\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_TODO']._serialized_start=29
  _globals['_TODO']._serialized_end=81
  _globals['_TODOLIST']._serialized_start=83
  _globals['_TODOLIST']._serialized_end=120
  _globals['_CREATETODOREQUEST']._serialized_start=122
  _globals['_CREATETODOREQUEST']._serialized_end=156
  _globals['_UPDATETODOREQUEST']._serialized_start=158
  _globals['_UPDATETODOREQUEST']._serialized_end=223
  _globals['_DELETETODOREQUEST']._serialized_start=225
  _globals['_DELETETODOREQUEST']._serialized_end=256
  _globals['_DELETETODORESPONSE']._serialized_start=258
  _globals['_DELETETODORESPONSE']._serialized_end=295
  _globals['_TODOSERVICE']._serialized_start=298
  _globals['_TODOSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
